/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class engine_water_WaterRender */

#ifndef _Included_engine_water_WaterRender
#define _Included_engine_water_WaterRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     engine_water_WaterRender
 * Method:    setBitmap
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_engine_water_WaterRender_setBitmap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     engine_water_WaterRender
 * Method:    render
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_engine_water_WaterRender_render
  (JNIEnv *, jclass, jobject);

/*
 * Class:     engine_water_WaterRender
 * Method:    drop
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_engine_water_WaterRender_drop
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     engine_water_WaterRender
 * Method:    flip
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_engine_water_WaterRender_flip
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
